// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Novibet.Library.Models;

namespace Novibet.API.Data
{
    public partial class IPDetailsDBContext : DbContext
    {
        public IPDetailsDBContext()
        {
        }

        public IPDetailsDBContext(DbContextOptions<IPDetailsDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<IPDetails> Ipdetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IPDetails>(entity =>
            {
                entity.HasKey(e => e.Ip);

                entity.ToTable("IPDetails");

                entity.Property(e => e.Ip)
                    .HasMaxLength(50)
                    .HasColumnName("IP");

                entity.Property(e => e.City).HasMaxLength(50);

                entity.Property(e => e.Continent).HasMaxLength(50);

                entity.Property(e => e.Country).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}